### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by CyberiumShadow** [joshmeney/up-new-tab-search#1]
Hey o/

Thought I'd give this a try and see if I could get it to build on my machine.

When running `npm run build`, I've been getting this error

```
Creating an optimized production build

Failed to compile.

Error: Expected an opening square bracket.
```

**Comment by joshmeney** [comment]
Hey there,

This should now be fixed, try give the latest version a go.

Basically it was an issue with the Tailwindcss purge settings not being configured properly. I was only playing around with this in `npm run dev` which doesn't run the purge so I never hit it.

Let me know if you're still having issues though.

**Comment by CyberiumShadow** [comment]
Might be a build config issue I think.

`npm run dev` works perfectly fine now and `npm run build` seems to successfully build, however when running the built version it seems like it loses all font and components compared to your image on twitter when running with `npm run dev`
![image](https://user-images.githubusercontent.com/4259904/89095684-948da780-d413-11ea-940c-dfaa8b5f9296.png)

**Comment by joshmeney** [comment]
Sorry, that was me being lazy on a Friday night, I just saw that the build completed and didn't check the output. Forgot to include the components directory in the purge css settings. Should be fixed now.

I also added the below instructions to the README, explaining how to set your savings goals and emojis:

To set your emojis and savings goals, you need to edit the `utils/accountDetails.js` file:

- The property key just needs to match your saving account name
- The emoji just needs to be the relevant emoji shortcode (minus the colons). You can find a list here: https://emojipedia.org
- The savings goals need to inputted as cents, not dollars
