### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by jamhos** [joshmeney/up-new-tab-search#2]
Hey Josh, this looks awesome! Thought I'd give it a go, but running in dev I get the following error right away:

![image](https://user-images.githubusercontent.com/59585318/92548934-8e54db80-f29b-11ea-9d34-6391ca252c67.png)

Don't worry too much, I assume it's just me - but if you have any tips then I'd greatly appreciate it!

Cheers,
James

**Comment by jamhos** [comment]
Ha, so it turned out to be an authentication issue, caused by a semi-colon at the end of the bearer token environment variable.
```javascript
NEXT_PUBLIC_UP_API_KEY = "up:yeah:yourrealapikeywillgoinhere";
```
Should be:
```javascript
NEXT_PUBLIC_UP_API_KEY = "up:yeah:yourrealapikeywillgoinhere"
```

**Comment by joshmeney** [comment]
Ah thank you, great pick up on the typo. Just merged in the pull request 👍
